from functions.dialogue import dialogue
from functions.portrait import portrait
from functions.image import image
import glob
from strings import *
from functions.preimage import preimage

image("resources/images/bg/house.png")
dialogue("???",'"Heeeeeeeyyy!!"')
dialogue("",'"I see an annoying girl running toward me from the distance, waving her arms in the air like she`s totally oblivious to any attention she might draw to herself."')
dialogue("",'"That girl is Sayori, my neighbor and good friend since we were children."')
dialogue("",'"You know, the kind of friend you`d never see yourself making today, but it just kind of works out because you`ve known each other for so long?"')
dialogue("",'"We used to walk to school together on days like this, but starting around high school she would oversleep more and more frequently, and I would get tired of waiting up."')
dialogue("",'"But if she`s going to chase after me like this, I almost feel better off running away."')
dialogue("",'"However, I just sigh and idle in front of the crosswalk and let Sayori catch up to me."')
portrait("resources/images/portrait/sayori/sayori1.png")
dialogue(sayoriname,'"Haaahhh...haaahhh..."')
dialogue(sayoriname,'"I overslept again!"')
dialogue(sayoriname,'"But I caught you this time!"')
dialogue(mcname, '"Maybe, but only because I decided to stop and wait for you."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori2.png")
dialogue(sayoriname,'"Eeehhhhh, you say that like you were thinking about ignoring me!"')
dialogue(sayoriname, '"That`s mean, '+mcname+'!"')
dialogue(mcname, '"Well, if people stare at you for acting weird then I don`t want them to think we`re a couple or something."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori3.png")
dialogue(sayoriname, '"Fine, fine."')
dialogue(sayoriname, '"But you did wait for me, after all."')
dialogue(sayoriname, '"I guess you don`t have it in you to be mean even if you want to~"')
dialogue(mcname, '"Whatever you say, Sayori..."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori4.png")
dialogue(sayoriname, '"Ehehe~"')
image("resources/images/bg/house.png")
dialogue("", '"We cross the street together and make our way to school."')
dialogue("", '"As we draw near, the streets become increasingly speckled with other students making their daily commute."')
portrait("resources/images/portrait/sayori/sayori5.png")
dialogue(sayoriname, '"By the way, '+mcname+'..."')
dialogue(sayoriname, '"Have you decided on a club to join yet?"')
dialogue(mcname, '"A club?"')
dialogue(mcname, '"I told you already, I`m really not interested in joining any clubs.')
dialogue(mcname, '"I haven`t been looking, either."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori6.png")
dialogue(sayoriname, '"Eh? That`s not true!"')
dialogue(sayoriname, '"You told me you would join a club this year!"')
dialogue(mcname, '"Did I...?"')
dialogue("", '"I`m sure it`s possible that I did, in one of our many conversations where I dismissively go along with whatever she`s going on about."')
dialogue("", '"Sayori likes to worry a little too much about me, when I`m perfectly content just getting by on the average while spending my free time on games and anime."')
dialogue(sayoriname, '"Uh-huh!"')
dialogue(sayoriname, '"I was talking about how I`m worried that you won`t learn how to socialize or have any skills before college."')
dialogue(sayoriname, '"Your happiness is really important to me, you know!"')
dialogue(sayoriname, '"And I know you`re happy now, but I`d die at the thought of you becoming a NEET in a few years because you`re not used to the real world!"')
dialogue(sayoriname, '"Don`t make me keep worrying about you..."')
dialogue(mcname, '"Alright, alright..."')
dialogue(mcname, '"I`ll look at a few clubs if it makes you happy."')
dialogue(mcname, '"No promises, though."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori7.png")
dialogue(sayoriname, '"Will you at least promise me you`ll try a little?"')
dialogue(mcname, '"Yeah, I guess I`ll promise you that."')
image("resources/images/bg/house.png")
portrait("resources/images/portrait/sayori/sayori8.png")
dialogue(sayoriname, '"Yaay~!"')
dialogue("", '"Why do I let myself get lectured by such a carefree girl?"')
dialogue("", '"More than that, I`m surprised I even let myself relent to her."')
dialogue("", '"I guess seeing her worry so much about me makes me want to ease her mind at least a little bit - even if she does exaggerate everything inside of her head."')
preimage("resources/prerenderedImages/black.txt")
image("resources/images/bg/class.png")
dialogue("", '"The school day is as ordinary as ever, and it`s over before I know it."')
dialogue("", '"After I pack up my things, I stare blankly at the wall, looking for an ounce of motivation."')
dialogue(mcname, '"Clubs..."')
dialogue("", '"Sayori wants me to check out some clubs."')
dialogue("", '"I guess I have no choice but to start with the anime club..."')
dialogue(sayoriname, '"Hellooo?"')
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori3.png")
dialogue(mcname, '"Sayori...?"')
dialogue("", '"Sayori must have come into the classroom while I was spacing out."')
dialogue("", '"I look around and realize that I`m the only one left in the classroom."')
dialogue(sayoriname, '"I thought I`d catch you coming out of the classroom, but I saw you just sitting here and spacing out, so I came in."')
dialogue(sayoriname, '"Honestly, you`re even worse than me sometimes... I`m impressed!"')
dialogue(mcname, '"You don`t need to wait up for me if it`s going to make you late to your own club."')
dialogue(sayoriname, '"Well, I thought you might need some encouragement, so I thought, you know..."')
dialogue(mcname, '"Know what?"')
dialogue(sayoriname, '"Well, that you could come to my club!"')
dialogue(mcname, '"Sayori..."')
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori8.png")
dialogue(sayoriname, '"Yeah??"')
dialogue(mcname, '"...There is no way I`m going to your club."')
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori2.png")
dialogue(sayoriname, '"Eeeehhhhh?! Meanie!"')
dialogue("", '"Sayori is vice president of the Literature Club."')
dialogue("", '"Not that I was ever aware that she had any interest in literature."')
dialogue("", '"In fact, I`m 99% sure she only did it because she thought it would be fun to help start a new club."')
dialogue("", '"Since she was the first one to show interest after the one who proposed the club, she inherited the title "Vice President"."')
dialogue("", '"That said, my interest in literature is guaranteed to be even less."')
dialogue(mcname, '"Yeah. I`m going to the anime club."')
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori7.png")
dialogue(sayoriname, '"C`mon, please?"')
dialogue(mcname, '"Why do you care so much, anyway?"')
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori2.png")
dialogue(sayoriname, '"Well..."')
dialogue(sayoriname, '"I kind of told the club yesterday I would bring in a new member..."')
dialogue(sayoriname, '"And Natsuki made cupcakes and everything..."')
dialogue(sayoriname, '"Ehehe..."')
dialogue(mcname, '"Don`t make promises you can`t keep!"')
dialogue("", '"I can`t tell if Sayori is really that much of an airhead, or if she`s so cunning as to have planned all of this out."')
dialogue("", '"I let out a long sigh."')
dialogue(mcname, "Fine... I'll stop by for a cupcake, okay?")
image("resources/images/bg/class.png")
portrait("resources/images/portrait/sayori/sayori8.png")
dialogue(sayoriname, "Yes! Let's go~!")
preimage("resources/prerenderedImages/black.txt")
image("resources/images/bg/corridor.png")
dialogue("", '"And thus, today marks the day I sold my soul for a cupcake."')
dialogue("", '"I dejectedly follow Sayori across the school and upstairs - a section of the school I rarely visit, being generally used for third-year classes and activities."')
dialogue("", '"Sayori, full of energy, swings open the classroom door."')
image("resources/images/bg/club.png")
portrait("resources/images/portrait/sayori/sayori9.png")
dialogue("", '"Everyone! The new member is here~!"')
dialogue("", '"I told you, don`t call me a `new member--`"')
image("resources/images/bg/club.png")
dialogue("", '"Eh? I glance around the room."')
portrait("resources/images/portrait/yuri/yuri1.png")
dialogue(yuriname, '"Welcome to the Literature Club. It`s a pleasure meeting you."')
dialogue(yuriname, '"Sayori always says nice things about you."')
image("resources/images/bg/club.png")
portrait("resources/images/portrait/multi/natsuki+yuri1.png")
dialogue(natsukiname, '"Seriously? You brought a boy?"')
dialogue(natsukiname, '"Way to kill the atmosphere."')
image("resources/images/bg/club.png")
portrait("resources/images/portrait/multi/monika+natsuki+yuri1.png")
dialogue(monikaname, '"Ah, [player]! What a nice surprise!"')
dialogue(monikaname, '"Welcome to the club!"')
dialogue("", '"All words escape me in this situation."')
dialogue("", '"This club..."')
dialogue("", '"...is full of incredibly cute girls!!"')
image("resources/images/bg/club.png")
portrait("resources/images/portrait/natsuki/natsuki1.png")
dialogue(natsukiname, '"What are you looking at?"')
dialogue(natsukiname, '"If you want to say something, say it."')
dialogue(mcname, "S-Sorry...")
portrait("resources/images/portrait/multi/natsuki+yuri2.png")
dialogue(yuriname, '"Natsuki..."')
image("resources/images/bg/club.png")
portrait("resources/images/portrait/multi/natsuki+yuri3.png")
dialogue(natsukiname, '"Hmph."')
